<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LigerShark.WebOptimizer.Sass" Version="3.0.147" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-rc.1.25451.107">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0-rc.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\catalog.proto" GrpcServices="Server,Client" />
    <Protobuf Include="Protos\management.proto" GrpcServices="Server,Client" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="dagangOnline.Tests/**/*.cs" />
    <Content Remove="dagangOnline.Tests/**" />
    <EmbeddedResource Remove="dagangOnline.Tests/**" />
    <None Remove="dagangOnline.Tests/**" />
  </ItemGroup>

</Project>
